import type { AppState, EvidenceItem, JobMatch, JobPosting } from "./types";

const evidence: EvidenceItem[] = [
  {
    id: "ev-role-current",
    category: "Employment history",
    claim: "Senior Data Analyst at Meridian Commerce, 2021–present",
    source: "Aisha_Rahman_Resume.pdf",
    reference: "Page 1 · Professional Experience",
    confidence: "High",
    confirmationStatus: "conflict",
    privacyLevel: "employer-approved",
    resumeUse: true,
    employerUse: true,
    classification: "Conflict requiring confirmation",
  },
  {
    id: "ev-role-old",
    category: "Employment history",
    claim: "Senior Data Analyst at Meridian Commerce, 2022–present",
    source: "Previous_Application.docx",
    reference: "Page 1 · Experience",
    confidence: "High",
    confirmationStatus: "conflict",
    privacyLevel: "private",
    resumeUse: false,
    employerUse: false,
    classification: "Conflict requiring confirmation",
  },
  {
    id: "ev-impact",
    category: "Measurable outcome",
    claim: "Reduced weekly reporting time by 18 hours through automated SQL and Power BI workflows",
    source: "Aisha_Rahman_Resume.pdf",
    reference: "Page 1 · Meridian Commerce · Bullet 2",
    confidence: "High",
    confirmationStatus: "confirmed",
    privacyLevel: "employer-approved",
    resumeUse: true,
    employerUse: true,
    classification: "Confirmed fact",
  },
  {
    id: "ev-leadership",
    category: "Leadership",
    claim: "Mentored two analysts and led analytics delivery across product, operations, and finance",
    source: "Product_Analytics_Portfolio.md",
    reference: "Section 3 · Operating model",
    confidence: "Medium",
    confirmationStatus: "confirmed",
    privacyLevel: "employer-approved",
    resumeUse: true,
    employerUse: true,
    classification: "Confirmed fact",
  },
  {
    id: "ev-skills",
    category: "Technical skills",
    claim: "SQL, Python, Power BI, experimentation, product metrics",
    source: "Aisha_Rahman_Resume.pdf",
    reference: "Page 2 · Skills",
    confidence: "High",
    confirmationStatus: "confirmed",
    privacyLevel: "employer-approved",
    resumeUse: true,
    employerUse: true,
    classification: "Confirmed fact",
  },
  {
    id: "ev-kubernetes",
    category: "Planned skill",
    claim: "Plans to learn Kubernetes",
    source: "Career_Planning_Conversation.json",
    reference: "Message 48",
    confidence: "High",
    confirmationStatus: "unconfirmed",
    privacyLevel: "private",
    resumeUse: false,
    employerUse: false,
    classification: "Planned skill",
  },
];

export const demoJobs: JobPosting[] = [
  {
    id: "job-northstar",
    sourceId: "mock-1",
    sourceLabel: "Grounded demo jobs",
    sourceKind: "mock",
    company: "Northstar Labs",
    title: "Senior Product Analyst",
    location: "Singapore",
    country: "Singapore",
    remotePolicy: "Hybrid",
    salaryLow: 7200,
    salaryHigh: 8800,
    salaryCurrency: "SGD",
    salaryPeriod: "monthly",
    visaFit: "Sponsorship may be available",
    seniority: "Senior",
    skills: ["SQL", "experimentation", "product metrics", "stakeholder management"],
    gaps: ["Direct fintech experience"],
    requisitionId: "NS-2418",
    canonicalUrl: "https://example.com/jobs/ns-2418",
    description: "Own product analytics and experimentation. Sponsorship considered for strong regional candidates.",
    postedAt: "2026-07-20",
    employmentType: "Full-time",
    industry: "Fintech",
    applicationSupport: "simulated",
  },
  {
    id: "job-kinetic",
    sourceId: "mock-1",
    sourceLabel: "Grounded demo jobs",
    sourceKind: "mock",
    company: "Kinetic Health",
    title: "Analytics Lead",
    location: "Singapore",
    country: "Singapore",
    remotePolicy: "On-site",
    salaryLow: 9000,
    salaryHigh: 10800,
    salaryCurrency: "SGD",
    salaryPeriod: "monthly",
    visaFit: "Sponsorship not mentioned",
    seniority: "Lead",
    skills: ["SQL", "Python", "team leadership", "strategy"],
    gaps: ["Budget ownership", "Healthcare domain depth"],
    requisitionId: "KH-883",
    canonicalUrl: "https://example.com/jobs/kh-883",
    description: "Lead a team of four analysts and set analytics strategy across customer journeys.",
    postedAt: "2026-07-18",
    employmentType: "Full-time",
    industry: "Health technology",
    applicationSupport: "assisted",
  },
  {
    id: "job-marina",
    sourceId: "mock-1",
    sourceLabel: "Grounded demo jobs",
    sourceKind: "mock",
    company: "Marina Market",
    title: "Product Manager, Data Products",
    location: "Singapore",
    country: "Singapore",
    remotePolicy: "Hybrid",
    salaryLow: 6800,
    salaryHigh: 8200,
    salaryCurrency: "SGD",
    salaryPeriod: "monthly",
    visaFit: "Sponsorship not mentioned",
    seniority: "Mid-level",
    skills: ["stakeholder management", "analytics", "roadmapping", "product discovery"],
    gaps: ["Direct product ownership", "Roadmap accountability", "User research"],
    requisitionId: "MM-510",
    canonicalUrl: "https://example.com/jobs/mm-510",
    description: "Shape internal data products with engineering, operations, and commercial partners.",
    postedAt: "2026-07-19",
    employmentType: "Full-time",
    industry: "E-commerce",
    applicationSupport: "simulated",
  },
  {
    id: "job-orbit",
    sourceId: "mock-1",
    sourceLabel: "Grounded demo jobs",
    sourceKind: "mock",
    company: "Orbit Systems",
    title: "Senior Business Intelligence Analyst",
    location: "Singapore",
    country: "Singapore",
    remotePolicy: "On-site",
    salaryLow: 6500,
    salaryHigh: 7800,
    salaryCurrency: "SGD",
    salaryPeriod: "monthly",
    visaFit: "Sponsorship clearly unavailable",
    seniority: "Senior",
    skills: ["SQL", "Power BI", "data modeling"],
    gaps: [],
    requisitionId: "OS-7730",
    canonicalUrl: "https://example.com/jobs/os-7730",
    description: "Applicants must already hold unrestricted Singapore work authorization. No visa sponsorship is available.",
    postedAt: "2026-07-17",
    employmentType: "Full-time",
    industry: "Enterprise software",
    applicationSupport: "external",
  },
];

const matches: JobMatch[] = [
  {
    id: "match-northstar",
    jobId: "job-northstar",
    decision: "Apply",
    interviewChance: "Medium",
    resumeVersion: "Singapore · Product Analytics",
    seniorityFit: "Good fit for Senior",
    salaryFit: "Within target range",
    visaFit: "Sponsorship may be available",
    gaps: ["Direct fintech experience"],
    evidenceQuality: "High",
    reasons: ["Strong SQL and experimentation evidence", "Cross-functional ownership is relevant"],
  },
  {
    id: "match-kinetic",
    jobId: "job-kinetic",
    decision: "Apply",
    interviewChance: "Low",
    resumeVersion: "Singapore · Analytics Leadership",
    seniorityFit: "Stretch fit for Lead",
    salaryFit: "Above current target",
    visaFit: "Sponsorship not mentioned",
    gaps: ["Budget ownership", "Healthcare domain depth"],
    evidenceQuality: "Medium",
    reasons: ["Mentoring supports a leadership transition", "No evidence of managing a four-person team"],
  },
  {
    id: "match-marina",
    jobId: "job-marina",
    decision: "Apply",
    interviewChance: "Low",
    resumeVersion: "Singapore · Career Change",
    seniorityFit: "Good fit for Mid-level, weak fit for Senior",
    salaryFit: "Within target range",
    visaFit: "Sponsorship not mentioned",
    gaps: ["Direct product ownership", "Roadmap accountability", "User research"],
    evidenceQuality: "Medium",
    reasons: ["Analytics and stakeholder work transfer", "Product ownership evidence is limited"],
  },
  {
    id: "match-orbit",
    jobId: "job-orbit",
    decision: "Skip",
    interviewChance: "Low",
    resumeVersion: "Singapore · Business Intelligence",
    seniorityFit: "Strong fit for Senior",
    salaryFit: "Within target range",
    visaFit: "Sponsorship clearly unavailable",
    gaps: [],
    evidenceQuality: "High",
    reasons: ["Employer explicitly refuses sponsorship"],
  },
];

const demoResumeContent = {
  personalized: false,
  sourceFile: "Aisha_Rahman_Resume.pdf",
  name: "Aisha Rahman",
  professionalTitle: "Senior Data Analyst",
  location: "Kuala Lumpur, Malaysia",
  relocation: "Open to Singapore relocation",
  email: "aisha@example.com",
  summary: "Experienced data analyst with six years of experience in SQL, product metrics, automated reporting, and cross-functional analytics delivery.",
  capabilityGroups: [{ label: "Skills", items: ["SQL", "Python", "Power BI", "Experimentation", "Product metrics", "Stakeholder management"] }],
  experiences: [
    { company: "Meridian Commerce", title: "Senior Data Analyst", startDate: "2021", endDate: "Present", bullets: ["Built dashboards and automated reports for business teams.", "Worked with stakeholders on analytics requests.", "Mentored two analysts on query quality and stakeholder communication."] },
    { company: "Meridian Commerce", title: "Data Analyst", startDate: "2018", endDate: "2021", bullets: ["Created recurring performance reporting and investigated operational trends using SQL and Excel."] },
  ],
  projects: ["Experiment measurement framework - Defined product success metrics and reusable SQL analysis templates."],
  earlierExperience: [],
  education: ["BSc Business Analytics - University of Malaya"],
  certifications: [],
  awards: [],
  languages: [],
} satisfies NonNullable<AppState["resumeContent"]>;

export const initialAppState: AppState = {
  user: { id: "demo-user", email: "aisha@example.com", displayName: "Aisha Rahman", locale: "en", createdAt: "2026-07-01" },
  onboardingComplete: false,
  consents: [
    { id: "consent-docs", userId: "demo-user", type: "document-analysis", granted: true, recordedAt: "2026-07-22" },
    { id: "consent-personal", userId: "demo-user", type: "personal-analytics", granted: true, recordedAt: "2026-07-22" },
    { id: "consent-anon", userId: "demo-user", type: "anonymous-product-analytics", granted: false, recordedAt: "2026-07-22" },
  ],
  preferences: {
    userId: "demo-user",
    countries: ["Singapore"],
    targetRoles: ["Senior Product Analyst", "Analytics Lead", "Product Manager"],
    openToCareerChange: true,
    requiresSponsorship: true,
    workModes: ["Hybrid", "On-site"],
    applicationMode: "Review Before Applying",
    salaryPriority: "Balanced",
    naturalLanguageRule: "Singapore jobs only. I am a Malaysian citizen and need an employer to consider an Employment Pass. Minimum salary SGD 7,000. Exclude gambling companies.",
    excludedCompanies: [],
    excludedIndustries: ["gambling"],
  },
  personalData: { userId: "demo-user", ageRange: "25–34", nationality: "Malaysian", currentCountry: "Malaysia", currentOccupation: "Senior Data Analyst", yearsExperience: 6 },
  salaryProfile: { userId: "demo-user", amount: 5600, currency: "SGD", period: "monthly", compensationType: "base", annualBonus: 6000, reduction: "No reduction" },
  workAuthorization: { userId: "demo-user", nationality: "Malaysian", currentCountry: "Malaysia", requiresSponsorship: true, existingAuthorization: "None for Singapore", acceptableVisaTypes: ["Employment Pass", "S Pass"], willingToRelocate: true, noticePeriod: "30 days", earliestStartDate: "2026-09-01" },
  documents: [
    { id: "doc-resume", userId: "demo-user", name: "Aisha_Rahman_Resume.pdf", type: "application/pdf", size: 184200, status: "analyzed", sourceKind: "resume", uploadedAt: "2026-07-22" },
    { id: "doc-old", userId: "demo-user", name: "Previous_Application.docx", type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", size: 96200, status: "analyzed", sourceKind: "other", uploadedAt: "2026-07-22" },
  ],
  conversations: [{ id: "conv-1", userId: "demo-user", name: "Career_Planning_Conversation.json", format: "json", status: "analyzed", importedAt: "2026-07-22" }],
  evidence,
  careerProfile: { userId: "demo-user", headline: "Senior Data Analyst moving toward product analytics", summary: "Six years in analytics with production reporting ownership, experimentation exposure, and cross-functional leadership.", employmentHistory: evidence.slice(0, 2), education: [], projects: [evidence[2]], skills: [evidence[4]], transferableSkills: ["Stakeholder management", "Analytical problem-solving", "Cross-functional delivery"], careerInterests: ["Product analytics", "Data products"], completeness: 82 },
  careerAssessments: [
    { id: "level-1", targetRole: "Senior Product Analyst", recommendedLevel: "Senior", currentLevel: "Senior", experiencePosition: "Within typical range", strengths: ["6 years of relevant analytics work", "Production SQL and reporting ownership", "Cross-functional leadership"], gaps: ["Limited direct fintech exposure"], confidence: "High", evidenceIds: ["ev-impact", "ev-leadership", "ev-skills"] },
    { id: "level-2", targetRole: "Product Manager", recommendedLevel: "Mid-level", currentLevel: "Mid-level", experiencePosition: "Below typical range", strengths: ["Strong analytics foundation", "Stakeholder management transfers well"], gaps: ["Direct product ownership", "Roadmap accountability", "User discovery evidence"], confidence: "Medium", evidenceIds: ["ev-leadership", "ev-skills"] },
  ],
  salaryAssessments: [{ id: "salary-1", role: "Senior Product Analyst", country: "Singapore", city: "Singapore", marketPosition: "Below Market", marketLow: 7000, marketHigh: 9000, recommendedLow: 7500, recommendedHigh: 8500, suggestedMinimum: 6500, currency: "SGD", period: "monthly", differencePercent: -12, confidence: "Medium", dataDate: "2026-07-01", sourceCategory: "Demonstration: seeded recent job-listing sample", demonstrationData: true }],
  jobs: demoJobs,
  matches,
  applications: [
    { id: "app-1", jobId: "job-northstar", company: "Northstar Labs", jobTitle: "Senior Product Analyst", location: "Singapore", source: "Grounded demo jobs", requisitionId: "NS-2418", resumeVersion: "Singapore · Product Analytics", status: "Needs Review", simulated: true },
    { id: "app-2", jobId: "job-kinetic", company: "Kinetic Health", jobTitle: "Analytics Lead", location: "Singapore", source: "Grounded demo jobs", requisitionId: "KH-883", resumeVersion: "Singapore · Analytics Leadership", status: "Recommended", simulated: true },
  ],
  resume: { id: "resume-1", userId: "demo-user", name: "Aisha Rahman · Master Resume", kind: "master", currentVersionId: "resume-v2" },
  resumeContent: demoResumeContent,
  resumeVersions: [
    { id: "resume-v1", resumeId: "resume-1", label: "Original · General Analytics", createdAt: "2026-07-22", evidenceIds: ["ev-impact", "ev-leadership", "ev-skills"] },
    { id: "resume-v2", resumeId: "resume-1", label: "Singapore · Product Analytics", targetCountry: "Singapore", targetRole: "Senior Product Analyst", targetJobId: "job-northstar", createdAt: "2026-07-22", evidenceIds: ["ev-impact", "ev-leadership", "ev-skills"] },
  ],
  resumeChanges: [
    { id: "change-1", resumeVersionId: "resume-v2", original: "Built dashboards and automated reports for business teams.", tailored: "Automated SQL and Power BI reporting across product, operations, and finance, reducing weekly reporting time by 18 hours.", reason: "Adds verified scope, tools, and impact that match the role.", evidenceIds: ["ev-impact", "ev-leadership"], status: "pending" },
    { id: "change-2", resumeVersionId: "resume-v2", original: "Worked with stakeholders on analytics requests.", tailored: "Led analytics delivery with product and operations partners, translating business questions into measurable product metrics.", reason: "Clarifies ownership without changing seniority or inventing outcomes.", evidenceIds: ["ev-leadership", "ev-skills"], status: "pending" },
  ],
  defenseCards: [{ id: "defense-1", resumeVersionId: "resume-v2", statement: "Reduced weekly reporting time by 18 hours", situation: "Weekly reporting depended on manual spreadsheet consolidation.", responsibility: "Own the reporting workflow and reliability.", actions: "Mapped source tables, wrote validation queries, and automated refreshes.", tools: "SQL, Power BI, Python", result: "18 hours saved each week, confirmed in the current resume.", likelyQuestion: "How did you measure the 18-hour reduction?", evidenceSource: "Aisha_Rahman_Resume.pdf · Page 1 · Bullet 2", userCanExplain: false }],
  schedule: { id: "schedule-1", userId: "demo-user", enabled: true, paused: false, time: "08:30", timeZone: "Asia/Kuala_Lumpur", dailyLimit: 8, lowChanceLimit: 2, lastRunAt: "2026-07-21T08:30:00+08:00", retryRule: "Retry once after 30 minutes; never retry captchas or assessments." },
  feedback: [],
  subscription: { userId: "demo-user", plan: "Free", quotas: { recommendations: 20, resumes: 3, applications: 5 }, usage: { recommendations: 11, resumes: 1, applications: 1 } },
  auditEvents: [{ id: "audit-1", userId: "demo-user", action: "application.prepared", targetId: "app-1", result: "allowed", model: "demo-structured-provider", promptVersion: "match-v1", evidenceIds: ["ev-impact", "ev-leadership", "ev-skills"], createdAt: "2026-07-22T09:15:00+08:00" }],
};
